Models/Association.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
namespace WeddingPlanner.Models;

public class Association
{
    [Key]
    public int AssociationId { get; set; }

    public int GuestId { get; set; }
    public Guest? Guest { get; set; }
    
    public int WeddingId { get; set; }
    public Wedding? Wedding { get; set; }

}

Models/ErrorViewModel.cs
namespace WeddingPlanner.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Guest.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace WeddingPlanner.Models;

public class Guest
{
    [Key]
    public int GuestId { get; set; }

    [Required(ErrorMessage = "is required")]
    [Display(Name = "First Name")]
    public string FirstName { get; set; }

    [Required(ErrorMessage = "is required")]
    [Display(Name = "Last Name")]
    public string LastName { get; set; }

    [Required(ErrorMessage = "is required")]
    [EmailAddress]
    public string Email { get; set; }

    [Required(ErrorMessage = "is required")]
    [MinLength(8, ErrorMessage = "must be at least 8 chars")]
    [DataType(DataType.Password)]
    public string Password { get; set; }

    [NotMapped]
    [Compare("Password", ErrorMessage = "doesn't match password")]
    [DataType(DataType.Password)]
    [Display(Name = "PW Confirm")]
    public string ConfirmPassword { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    public List<Association> Weddings { get; set; } = new List<Association>();
}

Models/LoginGuest.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

[NotMapped]
public class LoginGuest
{
    [Required(ErrorMessage = "is required")]
    [EmailAddress]
    [Display(Name = "Email")]
    public string LoginEmail { get; set; }

    [Required(ErrorMessage = "is required")]
    [MinLength(8, ErrorMessage = "must be at least 8 chars")]
    [DataType(DataType.Password)]
    [Display(Name = "Password")]
    public string LoginPassword { get; set; }

}

Models/MyContext.cs
#pragma warning disable CS8618
using Microsoft.EntityFrameworkCore;
namespace WeddingPlanner.Models;

public class MyContext : DbContext
{
    public MyContext(DbContextOptions options) : base(options) { }

    public DbSet<Guest> Guests { get; set; }
    public DbSet<Wedding> Weddings { get; set; }
    public DbSet<Association>Associations {get; set;}

}

Models/Wedding.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
namespace WeddingPlanner.Models;

public class Wedding
{
    public int WeddingId { get; set; }

    [Required(ErrorMessage = "is required")]
    [Display(Name = "Wedder One")]
    public string WedderOne { get; set; }

    [Required(ErrorMessage = "is required")]
    [Display(Name = "Wedder Two")]
    public string WedderTwo { get; set; }

    //need validation so no past dates are allowed
    [Required(ErrorMessage = "is required")]
    public DateTime Date { get; set; }

    [Required(ErrorMessage = "is required")]
    [Display(Name = "Wedding Address")]
    public string Address { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;


    public int GuestId { get; set; }
    public Guest? Planner { get; set; } 
    public List<Association> Guests { get; set; } = new List<Association>();

    public string WeddingCouple()
    {
        return WedderOne + " " + WedderTwo;
    }
}

Controllers/GuestController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WeddingPlanner.Models;
namespace WeddingPlanner.Controllers;

public class GuestController : Controller
{
    private MyContext _context;

    public GuestController(MyContext context)
    {
        _context = context;
    }

    [HttpGet("/")]
    public IActionResult LogAndReg()
    {
        return View("LogAndReg");
    }

    [HttpGet("/dashboard")]
    public IActionResult Dashboard()
    {
        List<Wedding> AllWeddings = _context.Weddings
        .Include(w=>w.Guests)
        .ThenInclude(w2=>w2.Guest)
        .ToList();
        return View("Dashboard", AllWeddings);
    }

    [HttpPost("/register")]
    public IActionResult Register(Guest newGuest)
    {   

        //add verifications later
        PasswordHasher<Guest> hashBrowns = new PasswordHasher<Guest>();
        newGuest.Password = hashBrowns.HashPassword(newGuest, newGuest.Password);

        _context.Guests.Add(newGuest);
        _context.SaveChanges();
        HttpContext.Session.SetInt32("UUID", newGuest.GuestId);

        return Dashboard();
    }

    [HttpPost("/login")]
    public IActionResult Login(LoginGuest loginGuest)
    {
        //add verifications later
        Guest? dbGuest = _context.Guests.FirstOrDefault(user => user.Email == loginGuest.LoginEmail);

        if(dbGuest == null)
        {
            ModelState.AddModelError("LoginEmail", "Not found");
            return LogAndReg();
        }

        PasswordHasher<LoginGuest> hashBrowns = new PasswordHasher<LoginGuest>();
        PasswordVerificationResult pwResult = hashBrowns.VerifyHashedPassword
        (loginGuest, dbGuest.Password, loginGuest.LoginPassword);

        if(pwResult == 0)
        {
            ModelState.AddModelError("LoginPassword", "is not correct");
            return LogAndReg();
        }

        HttpContext.Session.SetInt32("UUID", dbGuest.GuestId);
        return Dashboard();
    }

    //not working.. come back
    [HttpPost("/logout")]
    public IActionResult Logout()
    {
        HttpContext.Session.Clear();
        return View("LogAndReg");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WeddingPlanner.Models;

namespace WeddingPlanner.Controllers;

public class HomeController : Controller
{

    public IActionResult Privacy()
    {
        return View();
    }

}

Controllers/WeddingController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WeddingPlanner.Models;
namespace WeddingPlanner.Controllers;

public class WeddingController : Controller
{
    private MyContext db;

    public WeddingController(MyContext context)
    {
        db = context;
    }

    [HttpGet("/wedding/new")]
    public IActionResult WeddingForm()
    {
        return View("NewWedding");
    }

    [HttpGet("/wedding/detail/{wId}")]
    public IActionResult WeddingDetail(int wId)
    {
        Wedding? wed = db.Weddings
        .Include(w=>w.Guests)
        .ThenInclude(w=>w.Guest)
        .FirstOrDefault(w=>w.WeddingId == wId);

        if(wed == null)
        {
            return Redirect("Dashboard");
        }

        return View("WeddingDetail", wed);
    }

    [HttpPost("/wedding/create/")]
    public IActionResult CreateWedding(Wedding newWedding)
    {
        newWedding.GuestId = (int)HttpContext.Session.GetInt32("UUID");
        db.Weddings.Add(newWedding);
        db.SaveChanges();

        return WeddingDetail(newWedding.WeddingId);
    }

    [HttpPost("/wedding/rsvp/{wId}")]
    public IActionResult RSVP(int wId)
    {
        Association newAssociation = new Association(){
            WeddingId = wId,
            GuestId = (int)HttpContext.Session.GetInt32("UUID")
        };

        db.Associations.Add(newAssociation);
        db.SaveChanges();

        return RedirectToAction("Dashboard", "Guest");
    }

    [HttpPost("/wedding/unrsvp/{wId}")]
    public IActionResult UNRSVP(int wId)
    {
        Association? delAssociation = db.Associations
        .Include(w=>w.Wedding)
        .Include(w=>w.Guest)
        .FirstOrDefault(w=>w.WeddingId == wId);

        db.Associations.Remove(delAssociation);
        db.SaveChanges();
        
        return RedirectToAction("Dashboard", "Guest");
    }

    [HttpPost("/wedding/delete/{wId}")]
    public IActionResult Delete(int wId)
    {
        Wedding? delWed = db.Weddings.FirstOrDefault(w=>w.WeddingId == wId);

        db.Weddings.Remove(delWed);
        db.SaveChanges();
        
        return RedirectToAction("Dashboard", "Guest");
    }


}

Views/Guest/LogAndReg.cshtml
<partial name="_Register"></partial>
<partial name="_Login"></partial>

Views/Guest/_Login.cshtml
@model LoginGuest

<h3>Login</h3>
<form asp-controller="Guest" asp-action="Login" method="POST">
    <div class="mb-3">
        <label asp-for="LoginEmail"></label>
        <span asp-validation-for="LoginEmail" class="text-danger font-weight-bold"></span>
        <input asp-for="LoginEmail" class="form-control"/>
    </div>
        
    <div class="mb-3">
        <label asp-for="LoginPassword"></label>
        <span asp-validation-for="LoginPassword" class="text-danger font-weight-bold"></span>
        <input asp-for="LoginPassword" class="form-control"/>
    </div>
    
    <button>Login</button>
</form>

Views/Guest/_Register.cshtml
@model Guest

<h3>Register</h3>
<form asp-controller="Guest" asp-action="Register" method="POST">
    <div class="mb-3">
        <label asp-for="FirstName"></label>
        <span asp-validation-for="FirstName" class="text-danger font-weight-bold"></span>
        <input asp-for="FirstName" class="form-control"/>
    </div>

    <div class="mb-3">
        <label asp-for="LastName"></label>
        <span asp-validation-for="LastName" class="text-danger font-weight-bold"></span>
        <input asp-for="LastName" class="form-control"/>
    </div>
        
    <div class="mb-3">
        <label asp-for="Email"></label>
        <span asp-validation-for="Email" class="text-danger font-weight-bold"></span>
        <input asp-for="Email" class="form-control"/>
    </div>
        
    <div class="mb-3">
        <label asp-for="Password"></label>
        <span asp-validation-for="Password" class="text-danger font-weight-bold"></span>
        <input asp-for="Password" class="form-control"/>
    </div>
        <div class="mb-3">
        <label asp-for="ConfirmPassword"></label>
        <span asp-validation-for="ConfirmPassword" class="text-danger font-weight-bold"></span>
        <input asp-for="ConfirmPassword" class="form-control"/>
    </div>
    <button>Register</button>

</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/Dashboard.cshtml
@model List<Wedding>

<h1>Welcome to the Wedding Planner</h1>
<a asp-controller="Guest" asp-action="Logout">Logout</a>

<table class="table">
    <th>
        <tr>
            <td>Wedding</td>
            <td>Date</td>
            <td>Guest</td>
            <td>Action</td>
        </tr>
    </th>
    @foreach (Wedding wed in Model)
    {
        <tbody>
            <tr>
                <td><a asp-controller="Wedding" 
                asp-action="WeddingDetail"
                asp-route-wId="@wed.WeddingId">
                @wed.WedderOne + @wed.WedderTwo</a></td>
                <td>@wed.Date.ToString("MMM d, yyy")</td>
                <td>@wed.Guests.Count</td>
                @if(@wed.GuestId == Context.Session.GetInt32("UUID"))
                {
                    //make into form-button
                    <td><form asp-controller="Wedding"
                    asp-action="Delete"
                    asp-route-wId="@wed.WeddingId">
                    <button>Delete</button></form></td>
                }
                else if(wed.Guests.Any(wed=>wed.GuestId == Context.Session.GetInt32("UUID"))){
                    <td><form asp-controller="Wedding"
                    asp-action="UNRSVP"
                    asp-route-wId="@wed.WeddingId"
                    method="POST">
                    <button>Un-RSVP</button></form></td>
                }else{
                    <td><form asp-controller="Wedding"
                    asp-action="RSVP"
                    asp-route-wId="@wed.WeddingId"
                    method="POST">
                    <button>RSVP</button></form></td>
                }

                @* 
                -need to do sort of if and else if? to display
                the proper link to click
                -switch to proper link once one is selected
                -make proper changes in relationshp upon selection
                -maybe written as an action in the controller?
                 *@
            </tr>
        </tbody>
    }

</table>


<a asp-controller="Wedding" asp-action="WeddingForm" class="btn btn-primary">New Wedding</a>   

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeddingPlanner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WeddingPlanner.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WeddingPlanner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WeddingPlanner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Wedding/NewWedding.cshtml
@model Wedding

<h1>Plan Your Wedding</h1>

<a asp-controller="Guest" asp-action="Dashboard">Dashboard</a>
<a asp-controller="Guest" asp-action="Logout">Logout</a>

<form asp-controller="Wedding" asp-action="CreateWedding" method="POST">
    <div class="mb-3">
        <label asp-for="WedderOne"></label>
        <span asp-validation-for="WedderOne" class="text-danger font-weight-bold"></span>
        <input asp-for="WedderOne" class="form-control"/>
    </div>
    <div class="mb-3">
        <label asp-for="WedderTwo"></label>
        <span asp-validation-for="WedderTwo" class="text-danger font-weight-bold"></span>
        <input asp-for="WedderTwo" class="form-control"/>
    </div>
    <div class="mb-3">
        <label asp-for="Date"></label>
        <span asp-validation-for="Date" class="text-danger font-weight-bold"></span>
        <input asp-for="Date" class="form-control"/>
    </div>
    <div class="mb-3">
        <label asp-for="Address"></label>
        <span asp-validation-for="Address" class="text-danger font-weight-bold"></span>
        <input asp-for="Address" class="form-control"/>
    </div>
    <button>Create</button>

</form>

Views/Wedding/WeddingDetail.cshtml
@model Wedding

<h1>@Model.WedderOne and @Model.WedderTwo's Wedding</h1>

<a asp-controller="Guest" asp-action="Dashboard" class="btn btn-primary">Dashboard</a>
<a asp-controller="Guest" asp-action="Logout">Logout</a>

<h3>Date: @Model.Date.ToString("MMM d, yyy")</h3>

<h3>Guests:</h3>
@foreach (Association a in Model.Guests)
{
    <p>@a.Guest.FirstName</p>
}

@* 
-foreach to display guests names who will be attending said 
wedding...will likely need .includes statements and 
.thenIncludes statements in the controller
 *@